### ISSUE TITLE
Programmatically fetch the refresh tokens

### ISSUE THREAD

**Issue by kudos** [dawnerd/node-rdio#11]
The stuff in the readme should be done programmatically, refresh tokens are only valid for 12 hours.

Solid API deprecation period there from Rdio. Were they trying to avoid paying Mashery more money or something?

**Comment by dawnerd** [comment]
Agreed, will look into it.

**Comment by siboulet** [comment]
The refresh token is valid for 20 years.

http://www.rdio.com/developers/docs/web-service/oauth2/quick-ref/ref-oauth2-token-endpoint

**Comment by kudos** [comment]
@siboulet that is really not obvious (see snippet below), thanks for the clarification though.

```json
{
  "access_token": "<snip>",
  "token_type": "bearer",
  "expires_in": 43200,
  "refresh_token": "<snip>",
  "scope": ""
}
```

**Comment by dawnerd** [comment]
I still think we should support refreshing the token just in case. Nothing really stopping rdio from changing their minds next week.

**Comment by kudos** [comment]
Fair point :)

**Comment by siboulet** [comment]
Internally the module will update the refreshToken property after login. You can retrieve the new token from rdio.refreshToken. If you want to access the temporary access token you can also do so from rdio.accessToken.

```js
var Rdio = require('rdio');

var rdio = new Rdio({
  clientId: process.env.RDIO_CLIENT_ID,
  clientSecret: process.env.RDIO_CLIENT_SECRET,
  refreshToken: process.env.RDIO_REFRESH_TOKEN,
});

rdio.login(function() {
  console.log(rdio.refreshToken);
});
```

You can store that new refresh token and provide it for future module instantiation.

Alternatively you can also pass the accessToken directly when instantiating the module, in which case you don't have to call login().

I believe the app that uses node-rdio should be responsible for retrieving the refresh (or access) token (ie. an Express app using node-rdio as backend). Oauth2 needs external confirmation from the browser and a redirect URL to work. It doesn't seems trivial to implement at the node-rdio module level.
