### ISSUE TITLE
Simple, non-authenticated requests?

### ISSUE THREAD

**Issue by syropian** [dawnerd/node-rdio#12]
Is there a way to authenticate using just the client/secret and no refresh token? I don't need to make any authenticated calls, just simple ones. The rdio-simple node lib let me do this, but it currently hasn't been updated to support oauth2.

**Comment by dawnerd** [comment]
It's been a while since I've really used the rdio apis in depth, is there an example of one of the calls? I don't imagine it being very hard to add support in.

**Comment by syropian** [comment]
Sure, we do something like this:

```
rdio = new Rdio([KEY, SECRET])
    rdio.call("findUser", {
      vanityName: RDIO_USERNAME,
      extras: "lastSongPlayed"
    }, (err, res) ->
      if err
        msg.send err
        return
      track = res.result.lastSongPlayed
      trackName = track.name
      trackArtist = track.artist
      trackAlbum = track.album
      msg.send "Now playing: #{trackName} by #{trackArtist} on #{trackAlbum}"
    )
```

**Comment by ndimatteo** [comment]
This isn't working @syropian.

When I run my code, I'm getting the following error in the console:

````
Cannot merge array onto an object
````

and here's my code:
````javascript
var rdio = new Rdio(['xxxxxxxxxxxxxx', 'xxxxxxxxxxxxxx']);
	rdio.call('getHeavyRotation', {
		user:'s11484980',
		type:'albums',
		limit:'3'
	}, function(err, res) {
		if (err) {
			console.log(err);
		} else {
			console.log(res);
		}
	});

**Comment by dawnerd** [comment]
@ndimatteo @syropian Fixed in latest. I don't have time to write the documentation right now, but the example file should give you a good idea on how to tackle this. Basically the same as generating an access token. When making a request the second parameter controls if it requires authentication.

**Comment by dawnerd** [comment]
Also make sure you use the updated rdio methods, changed slightly from 2.0.0, Rdio() takes an object for the config, and call is now request. Sorry about that!

**Comment by ndimatteo** [comment]
@dawnerd It's not working for me...

Console error:

```
{ statusCode: 401,
  data: '{"error_description": "Invalid or expired access token", "error": "invalid_token"}' }
```

Here's my code:

``` javascript
var rdio = new Rdio();
    rdio.request({
    method: 'getHeavyRotation',
    user:'s11484980',
        type:'albums',
        limit:'3'
    }, false, function(err, res) {
        if (err) {
            console.log(err);
        } else {
            console.log(res);
        }
    });
```

**Comment by dawnerd** [comment]
Are you passing in a clientId and clientSecret? And are you calling getClientToken()?

**Comment by ndimatteo** [comment]
Yes, sorry I have the clientId and clientSecret passed higher up like so:

``` javascript
var Rdio = require('rdio')({
    rdio: {
        clientId: 'xxxxxxxxxxxx',
        clientSecret: 'xxxxxxxxxxxx'
    }
})
```

**Comment by ndimatteo** [comment]
wait, why do I need to call getClientToken() if it doesn't require auth?

**Comment by dawnerd** [comment]
From what I can tell rdio requires a client token. http://www.rdio.com/developers/docs/web-service/oauth2/auth-client/ref-oauth2-auth-client

getClientToken doesn't require the user to do anything so you could do it on app setup. I'm not sure how long the token lasts for though. Could probably use some more work around that.

**Comment by ndimatteo** [comment]
Ahh, gotcha. Seems a bit odd. Either way, thanks for the quick replies & update. Glad to have this working!
