### ISSUE TITLE
Start value causes invalid signature error

### ISSUE THREAD

**Issue by dasevilla** [dawnerd/node-rdio#7]
Received a support request mentioning your library and wasn't able to reproduce it elsewhere. The problem is when searching with `start=0`:

    method: 'search'
    , query: 'diplo'
    , start: 0
    , count: 20
    , types: 'Track'

If you include a `start` value greater than `0` or don't include it at all, it works. My guess is whatever OAuth library you're using isn't including the `start` parameter if it's falsey.

**Comment by dawnerd** [comment]
Now fixed in v3.0.0
